const instances=[
 {name:'Vanilla Survival',version:'1.21.8',loader:'Vanilla',icon:'⛏'},
 {name:'Create Adventures',version:'1.20.1',loader:'Fabric',icon:'⚙'},
 {name:'Performance+',version:'1.21.1',loader:'Fabric',icon:'⚡'},
 {name:'Better Minecraft',version:'1.20.1',loader:'Forge',icon:'◆'}
];
const featured=[['Sodium','Performance mod','⚡'],['Create','Automation & engineering','⚙'],['Fabric API','Modding library','▦'],['Lithium','Server optimization','◆']];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function card(i){return `<article class="instance"><div class="instance-cover">${i.icon}</div><h4>${i.name}</h4><p>${i.version} · ${i.loader}</p><div class="instance-footer"><span>Ready</span><button class="play" data-launch="${i.name}">▶ Play</button></div></article>`}
function render(){ $('#recentGrid').innerHTML=instances.slice(0,3).map(card).join(''); $('#instanceGrid').innerHTML=instances.map(card).join(''); $('#discoverGrid').innerHTML=featured.map(x=>`<article class="instance"><div class="instance-cover">${x[2]}</div><h4>${x[0]}</h4><p>${x[1]}</p><div class="instance-footer"><span>Featured</span><button class="play">View</button></div></article>`).join(''); bindPlay() }
function bindPlay(){ $$('[data-launch]').forEach(b=>b.onclick=()=>launch(b.dataset.launch)); }
async function bridge(){try{let r=await fetch('http://127.0.0.1:47521/health',{signal:AbortSignal.timeout(800)});return r.ok}catch{return false}}
async function launch(name='Minecraft'){const status=$('#launchStatus');status.textContent=`Starting ${name}…`;try{const cmd=localStorage.getItem('minecraftCommand')||'minecraft://';const r=await fetch('http://127.0.0.1:47521/launch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,command:cmd})});const j=await r.json();status.textContent=j.message||'Minecraft launch requested.'}catch{window.location.href='minecraft://';status.textContent='If Minecraft did not open, install/start the local launcher bridge in /launcher.'}}
function show(page){$$('.page').forEach(p=>p.classList.toggle('active-page',p.id===page));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const labels={home:['Home','Your Minecraft worlds, one click away.'],instances:['Instances','Manage your local Minecraft profiles.'],discover:['Discover','Explore mods and modpacks.'],settings:['Settings','Configure the desktop launcher bridge.']};$('#page-title').textContent=labels[page][0];$('#page-subtitle').textContent=labels[page][1]}
$$('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.page));$$('[data-page-link]').forEach(b=>b.onclick=()=>show(b.dataset.pageLink));$('#launchMain').onclick=()=>launch();$('#themeBtn').onclick=()=>document.body.classList.toggle('light');$('#newInstance').onclick=()=>alert('Add your instance creation flow here.');$('#instanceSearch').oninput=e=>{$$('#instanceGrid .instance').forEach(x=>x.style.display=x.innerText.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')};$('#saveSettings').onclick=()=>{localStorage.setItem('minecraftCommand',$('#minecraftCommand').value);$('#saveStatus').textContent='Saved.'};$('#minecraftCommand').value=localStorage.getItem('minecraftCommand')||'minecraft://';
render();bridge().then(ok=>$('#launchStatus').textContent=ok?'Launcher bridge: connected ✓':'Launcher bridge: offline — use /launcher to enable desktop launching.');
